services:
  translate:
    duckduckgo:
      url: https://duckduckgo.com/translation.js
    yandex:
      url: https://translate.api.cloud.yandex.net/translate/v2
      authorization: Bearer t1.9euelZrHxo6QzY7KlseYmZCNjYudnO3rnpWayMySk4mdkpWciYmJj8fIl8nl8_dWJTFu-e9HUWhe_d3z9xZULm7570dRaF79.4mFdmGO1LNEYqxZepHolCaM38aM6r0tjhqm4Z1WEOrEPX7Tq2yr3zMwGV1qol5HzTGn8VvArXq1Cz9QQ7ZMhAQ
      folder: b1gnbjk2q1k6bmd1le37

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  profiles:
    active: prod
server:
  port: ${PORT:8080}