services:
  translate:
    duckduckgo:
      url: https://duckduckgo.com/translation.js
    yandex:
      url: https://translate.api.cloud.yandex.net/translate/v2
      authorization: Bearer t1.9euelZqQzZmLjM6cksmQlcyMksiMyu3rnpWayMySk4mdkpWciYmJj8fIl8nl9PdUQy5u-e8bYHHr3fT3FHIrbvnvG2Bx6w.FIDZTsY3RCy7MMN1cWcmWCrgbs2vVo7nKmljZTYQOTC7i3YVcDs32DAuxnP4heKfIeD0ZT3lErz81MVq7jHaCw
      folder: b1gnbjk2q1k6bmd1le37
      auth-token: insert ur token here

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

  profiles:
    active: prod
server:
  port: ${PORT:8080}