services:
  translate:
    yandex:
      url: https://translate.api.cloud.yandex.net/translate/v2
      authorization: Bearer t1.9euelZrMz5SJz4mLkZybzMbIlImajO3rnpWayMySk4mdkpWciYmJj8fIl8nl8_caDTdu-e8tOlA9_d3z91o7NG757y06UD39.ekVBDwn1OdOt5eQfKb775bWTa4mHejjytsyBbTnAu5St5cDWr5RRbroI2MqqxuFAttiLxZTPb9p11T4ab51vDw
      folder: b1gnbjk2q1k6bmd1le37

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false